-- Rename the tenant vocabulary to company, and move every column to snake_case.
--
-- Hand-written on purpose. Prisma's autogenerated diff for a rename is a DROP
-- plus a CREATE, which would destroy every row. Every statement here is a
-- RENAME: no data is read, written or lost.
--
-- Constraint and index names are renamed too. Prisma derives its default
-- constraint names from the *database* column names, so after `companyId
-- @map("company_id")` it expects `users_company_id_idx`, not
-- `users_tenantId_idx`. Leaving the old names in place would show up as
-- permanent drift on the next `prisma migrate dev`.

-- Tables
ALTER TABLE "tenants" RENAME TO "companies";

-- Columns: companies
ALTER TABLE "companies" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "companies" RENAME COLUMN "updatedAt" TO "updated_at";

-- Columns: users
ALTER TABLE "users" RENAME COLUMN "tenantId"  TO "company_id";
ALTER TABLE "users" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "users" RENAME COLUMN "updatedAt" TO "updated_at";

-- Primary keys (renaming the constraint renames its backing index too)
ALTER TABLE "companies" RENAME CONSTRAINT "tenants_pkey" TO "companies_pkey";

-- Foreign key
ALTER TABLE "users" RENAME CONSTRAINT "users_tenantId_fkey" TO "users_company_id_fkey";

-- Indexes
ALTER INDEX "tenants_slug_key"         RENAME TO "companies_slug_key";
ALTER INDEX "users_tenantId_idx"       RENAME TO "users_company_id_idx";
ALTER INDEX "users_tenantId_email_key" RENAME TO "users_company_id_email_key";
