import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { withCompany } from "../src/index.ts";
import { seedCompany, truncateAll, type SeededCompany } from "./helpers.ts";

/**
 * The webhook key is the whole routing story, so its two properties are worth
 * asserting rather than assuming.
 *
 * It is generated by a database DEFAULT, which is the unusual choice here: the
 * point is that no row can exist without one, including rows written by a
 * migration or by a future code path that has not thought about webhooks. The
 * risk that buys is a default evaluated *once* instead of per row - which would
 * hand every company in the installation the same webhook URL, and would look
 * completely fine until two of them received each other's messages.
 *
 * These are not isolation tests. They assert what the column guarantees, not
 * what a policy refuses, so they live outside rls-isolation.test.ts and use the
 * ORM freely.
 */

let alpha: SeededCompany;
let beta: SeededCompany;

beforeEach(async () => {
  await truncateAll();
  alpha = await seedCompany("alpha");
  beta = await seedCompany("beta");
});

afterEach(async () => {
  await truncateAll();
});

async function createIntegration(company: SeededCompany): Promise<string> {
  return withCompany(company.id, async (db, companyId) => {
    const integration = await db.integration.create({
      data: { companyId, provider: "WHATSAPP_CLOUD", label: "Primary" },
      select: { webhookKey: true },
    });
    return integration.webhookKey;
  });
}

describe("webhook keys", () => {
  it("gives every integration a different one", async () => {
    /*
     * The claim the migration rests on. A volatile DEFAULT is evaluated once
     * per row; a stable one would not be, and the unique index would only
     * catch it on the second insert - by which time a shipped migration had
     * already given every existing company the same key.
     */
    const first = await createIntegration(alpha);
    const second = await createIntegration(beta);

    expect(first).not.toBe(second);
  });

  it("is written without anyone asking for it", async () => {
    /*
     * Nothing in the application supplies this value. If the default were ever
     * dropped, the column is NOT NULL and this would fail rather than silently
     * producing rows Meta can never reach.
     */
    const key = await createIntegration(alpha);

    expect(key).toMatch(/^[0-9a-f]{32}$/);
  });

  it("carries no identifier that could be worked backwards", async () => {
    /*
     * The reason it is not derived from the row's own ids. Meta stores this URL
     * on its servers and customers screenshot it, so a key containing a company
     * id would publish one.
     */
    const key = await createIntegration(alpha);

    expect(key).not.toContain(alpha.id);
    expect(key).not.toContain(alpha.slug);
  });
});
