/**
 * What we write into a button, and what a tap three days later resolves to.
 *
 * ===========================================================================
 * This is the one decision in the phase with no migration behind it
 * ===========================================================================
 *
 * WhatsApp buttons never expire in the chat. A customer scrolls up three days,
 * taps "Yes" on a message from a flow that finished on Tuesday, and what
 * arrives is whatever string we put in the id - unchanged, because it has been
 * sitting in their history since we sent it. There is no way to rewrite it, no
 * way to invalidate it, and no way to ask Meta what it used to mean.
 *
 * So an id meaning "yes" is ambiguous by construction. It cannot say which
 * question it answered, which run of the flow it belonged to, or whether that
 * run is still live - and a runtime that receives one has no choice but to
 * guess. The guess it would make is the dangerous one: advance whatever run
 * this conversation currently has, from wherever it currently is, on the
 * strength of a tap that answered a different question entirely.
 *
 * Encoding the run and the node makes the stale tap RECOGNISABLE. It resolves
 * to a node the run has already left, or to a run that has ended, and the
 * engine declines it deliberately and records that it did. That is the whole
 * job of this module.
 *
 * ===========================================================================
 * The shape
 * ===========================================================================
 *
 *   f1.r.<runId>.<nodeId>.<choice>     a reply inside a running flow
 *   f1.e.<versionId>.<nodeId>          an entry point, before any run exists
 *
 * `f1` is a scheme version and is checked first. Ids from this scheme are in
 * customers' chat histories for ever, so the second scheme cannot be a change
 * to the first - it has to be a new prefix that the old decoder rejects and
 * the new one recognises alongside `f1`. That is the only migration available
 * for a value we cannot reach, which is why the tag is here from the start
 * rather than added when it is first needed.
 *
 * Two kinds rather than one, because the entry point genuinely has no run: an
 * approved template's quick-reply button is what STARTS a flow, and the run it
 * starts does not exist when the button is written. It names the flow version
 * instead - which is also what makes "the version was unpublished since" a
 * recognisable outcome rather than a run that begins on a draft somebody was
 * halfway through editing.
 *
 * ===========================================================================
 * Why parsing is total, and never throws
 * ===========================================================================
 *
 * The input is a string a customer's phone sent us. It may be from another
 * system entirely, from a template somebody wrote by hand in Meta's UI, or
 * corrupt. Every one of those is an ordinary Tuesday, not an exception - and
 * an inbound webhook is the worst place in the system to throw: nobody is
 * watching, the delivery retries, and the customer's message is lost.
 *
 * So this returns a discriminated union with `not_ours` and `malformed` as
 * first-class answers, and the caller decides. Nothing here logs, throws or
 * reaches for I/O.
 */

/** The scheme tag. A different scheme gets a different tag, never a new field. */
export const BUTTON_ID_SCHEME = "f1";

const SEPARATOR = ".";

/**
 * Meta's cap on a reply button id is 256 and on a list row id is 200. We fit
 * inside the smaller of the two with room to spare, and refuse to emit
 * anything that would not - a truncated id is a tap that decodes as malformed
 * for ever.
 */
export const MAX_BUTTON_ID_LENGTH = 200;

/**
 * Caps on the two author-supplied parts.
 *
 * Node ids and choice keys are generated by the builder rather than typed, so
 * these are a guard against a future generator rather than against a person.
 * They exist because the failure they prevent is silent and permanent: a long
 * node id pushes the whole string past Meta's limit, Meta truncates or refuses,
 * and every button that flow ever sent is undecodable.
 */
const MAX_NODE_ID_LENGTH = 32;
const MAX_CHOICE_LENGTH = 40;

/**
 * Room for a cuid, which is 25 characters, plus slack for whatever generates
 * ids next. Named rather than inlined because both id kinds use it and the two
 * drifting apart would make one kind encodable and the other not.
 */
const MAX_REF_LENGTH = 40;

/**
 * The character set for the parts, which is also why the separator is safe.
 *
 * cuid() emits [a-z0-9] and the builder generates node ids and choice keys in
 * the same alphabet plus a dash and an underscore. A dot cannot appear inside
 * a part, so splitting on it cannot produce a part that was never written -
 * which is the failure a permissive character set would allow: a choice key
 * containing a dot would decode as an id with an extra field, and the tap that
 * carried it would be refused as malformed by the very flow that sent it.
 */
const PART_PATTERN = /^[A-Za-z0-9_-]+$/;

export type ButtonRef =
  /** A tap on a message this run sent. Names the run and the node that asked. */
  | { kind: "reply"; runId: string; nodeId: string; choice: string }
  /** A tap on an approved template's quick reply. Names the version to start. */
  | { kind: "entry"; versionId: string; nodeId: string };

export type ButtonIdParse =
  | { ok: true; ref: ButtonRef }
  /**
   * Not written by us at all.
   *
   * Distinct from malformed on purpose. A customer with two vendors in their
   * WhatsApp taps a button from somebody else's system and the payload lands
   * in our webhook; that is not an error and must not be recorded as one, or
   * the flow's own error count becomes a count of other people's buttons.
   */
  | { ok: false; reason: "not_ours" }
  /**
   * Ours by its prefix, and unreadable after that.
   *
   * Worth separating because it is the shape of a bug on our side - a
   * generator that changed, a truncation, an id built by hand - and it is the
   * one an operator should be able to find.
   */
  | { ok: false; reason: "malformed" };

function isPart(value: string | undefined, max: number): value is string {
  return (
    value !== undefined &&
    value.length > 0 &&
    value.length <= max &&
    PART_PATTERN.test(value)
  );
}

/**
 * The id for a reply button or list row inside a running flow.
 *
 * Throws, unlike the parser, and the asymmetry is deliberate: this runs while
 * we are BUILDING a message, with our own values, before anything has been
 * sent. An id too long to decode is a bug that should stop a send, not one
 * that should reach a customer's chat history and sit there for ever.
 */
export function encodeReplyButtonId(input: {
  runId: string;
  nodeId: string;
  choice: string;
}): string {
  assertPart("runId", input.runId, MAX_REF_LENGTH);
  assertPart("nodeId", input.nodeId, MAX_NODE_ID_LENGTH);
  assertPart("choice", input.choice, MAX_CHOICE_LENGTH);

  const id = [BUTTON_ID_SCHEME, "r", input.runId, input.nodeId, input.choice].join(
    SEPARATOR,
  );

  assertLength(id);
  return id;
}

/** The payload for an approved template's quick reply, which starts a run. */
export function encodeEntryButtonId(input: {
  versionId: string;
  nodeId: string;
}): string {
  assertPart("versionId", input.versionId, MAX_REF_LENGTH);
  assertPart("nodeId", input.nodeId, MAX_NODE_ID_LENGTH);

  const id = [BUTTON_ID_SCHEME, "e", input.versionId, input.nodeId].join(SEPARATOR);

  assertLength(id);
  return id;
}

function assertPart(name: string, value: string, max: number): void {
  if (!isPart(value, max)) {
    throw new Error(
      `Flow button ${name} must be 1-${max} characters of [A-Za-z0-9_-]; got ${JSON.stringify(value)}`,
    );
  }
}

function assertLength(id: string): void {
  if (id.length > MAX_BUTTON_ID_LENGTH) {
    throw new Error(
      `Flow button id is ${id.length} characters, over Meta's ${MAX_BUTTON_ID_LENGTH} limit: ${id}`,
    );
  }
}

/**
 * Read whatever arrived. Never throws.
 *
 * The length check comes first and is not a formality. Meta caps the id, so a
 * value over the cap did not come from the encoders above - and refusing it
 * before splitting means a pathological input cannot cost anything.
 */
export function parseButtonId(raw: string | null | undefined): ButtonIdParse {
  if (typeof raw !== "string" || raw.length === 0) {
    return { ok: false, reason: "not_ours" };
  }

  if (raw.length > MAX_BUTTON_ID_LENGTH) {
    return { ok: false, reason: "not_ours" };
  }

  const parts = raw.split(SEPARATOR);

  if (parts[0] !== BUTTON_ID_SCHEME) {
    return { ok: false, reason: "not_ours" };
  }

  const kind = parts[1];

  if (kind === "r") {
    const [, , runId, nodeId, choice] = parts;

    /*
     * Exactly five parts. A sixth would mean a separator inside a part, which
     * PART_PATTERN forbids on the way out - so an id with one did not come
     * from here and must not be read as though the extra field were absent.
     */
    if (
      parts.length !== 5 ||
      !isPart(runId, MAX_REF_LENGTH) ||
      !isPart(nodeId, MAX_NODE_ID_LENGTH) ||
      !isPart(choice, MAX_CHOICE_LENGTH)
    ) {
      return { ok: false, reason: "malformed" };
    }

    return { ok: true, ref: { kind: "reply", runId, nodeId, choice } };
  }

  if (kind === "e") {
    const [, , versionId, nodeId] = parts;

    if (
      parts.length !== 4 ||
      !isPart(versionId, MAX_REF_LENGTH) ||
      !isPart(nodeId, MAX_NODE_ID_LENGTH)
    ) {
      return { ok: false, reason: "malformed" };
    }

    return { ok: true, ref: { kind: "entry", versionId, nodeId } };
  }

  /*
   * Our scheme tag and a kind we do not know. Malformed rather than not_ours:
   * the prefix says we wrote it, so this is a deploy that emitted a kind an
   * older reader does not have - which is exactly the thing worth seeing.
   */
  return { ok: false, reason: "malformed" };
}
